name: EzChestShop
version: ${project.version}
main: me.deadlight.ezchestshop.EzChestShop
api-version: 1.14
depend: [Vault]
softdepend:
  - WildChests
  - WorldGuard
  - Slimefun #in case just to load after the Slimefun
  - Multiverse-Core #preventing null worlds
authors: [Dead_Light, ElitoGame]
description: ${project.description}
commands:
  chestshop:
  csadmin:
  checkprofits:
    description: Check all your shop profits that you made offline!
    aliases:
      - cp
